version: '3'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
      - '/home/qmi/common/qmicerts:/etc/qlikcerts'
  fastapi:
    image: 'qlik-chatgpt:latest'
    restart: unless-stopped
    environment:
      CHAT_GPT_TOKEN: ${CHAT_GPT_TOKEN}
    ports:
      - '8000:8000'   
    volumes:
      - ./app:/code      